version: "3"

services:
  slidev:
    container_name: slidev
    networks:
      default:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./src:/work
    tty: true
    restart: always
